export const jurisprudenciaExtra = [
  {
    rit: "C-11.798-2022",
    ruc: "",
    caratula: "Carrillo v/s Banco del Estado de Chile",
    tribunal: "3° Juzgado de Letras del Trabajo de Santiago",
    tipo: "sentencia",
    materia: "laboral",
    contenido: "SENTENCIA. ROL C-11.798-2022. En la causa CARRILLO V/S BANCO DEL ESTADO DE CHILE, el 3° Juzgado de Letras del Trabajo de Santiago, en autos seguidos a pedido de DON JORGE EDUARDO CARRILLO GONZALEZ con el BANCO DEL ESTADO DE CHILE, sobre TUTELA DE DERECHOS, en sentencia de fecha 30 de agosto de 2022, dictada en el estrado, declaro: PRIMERO: Que se acoge la demanda y se declara que el despido del actor se encuentra amparado en la causal de necesidades de la empresa, consistente en reordenamiento institucional y racionalizacion de procesos. SEGUNDO: Se declara aplicable al actor el tope indemnizatorio maximo previsto en el articulo 163 del Codigo del Trabajo, equivalente a trescientos treinta dias de remuneracion. TERCERO: Se condena al demandado al pago al actor de las siguientes prestaciones: a) Indemnizacion sustitutiva del aviso previo por la suma de DOS MILLONES SEISCIENTOS CUARENTA Y SIETE MIL TRESCIENTOS TRECE PESOS ( mediante la aplicacion del articulo 165 del Codigo del Trabajo; b) Indemnizacion por anos de servicio por la suma de VEINTINUEVE MILLONES UNO CUARENTA MIL CUATROCIENTOS SETENTA Y NUEVE PESOS ($ mediante la aplicacion del articulo 163 del Codigo del Trabajo; c) Feriado legal proporcional correspondiente al ano 2022 por la suma de UN MILLON CIENTO CUARENTA Y SIETE MIL SETECIENTOS SESENTA PESOS ($1.147.760); d) Indemnizacion por desahucio correspondiente al ano 2021 por la suma de SETENTA Y UN MIL DOSCIENTOS SESENTA PESOS ($71.260); e) Indemnizacion por desahucio correspondiente al ano 2022 por la suma de CIENTO CINCUENTA Y UN MIL SEISCIENTOS CINCUENTA PESOS ($151.650); f) Ahorro previsional voluntario, mas reajustes e intereses legales.",
    extracto: "El despido fundado en reordenamiento institucional y racionalizacion de procesos constituye necesidades de la empresa validas si se acreditan fehacientemente. Se aplica el tope de 330 dias de remuneracion del Art. 163 CT.",
    fallo: "Se acoge demanda en parte. Se declara procedente el despido por necesidades de la empresa. Se condena a pagar indemnizaciones con tope de 330 dias.",
    fundamento: "Art. 159 N° 6°, Art. 160, Art. 163, Art. 165, Art. 168 bis, Art. 168 ter del Codigo del Trabajo. Reordenamiento institucional como necesidad de la empresa. Acreditacion de la causal.",
    normasAplicadas: "Art. 159 N° 6° CT, Art. 160 CT, Art. 163 CT, Art. 165 CT, Art. 168 bis CT, Art. 168 ter CT",
    fechaSentencia: "2022-08-30",
  },
  {
    rit: "C-6.432-2022",
    ruc: "",
    caratula: "Bustos v/s Transportes JKH Limitada",
    tribunal: "1° Juzgado de Letras del Trabajo de San Bernardo",
    tipo: "sentencia",
    materia: "laboral",
    contenido: "SENTENCIA. ROL C-6.432-2022. En la causa BUSTOS V/S TRANSPORTES JKH LIMITADA, el 1° Juzgado de Letras del Trabajo de San Bernardo, en autos seguidos a pedido de DON MARCELO GUILLERMO BUSTOS ARAYA con TRANSPORTES JKH LIMITADA, sobre TUTELA DE DERECHOS, en sentencia de fecha 10 de noviembre de 2022, declaro: PRIMERO: Que se declara fundada la demanda. SEGUNDO: Que se declara que el actuar del demandado, al exigir al recurrente que continuara conduciendo su camion pese a encontrarse con sintomatologia de COVID-19 y sin entregarle los implementos necesarios para evitar el contagio de sus companeros, constituye un acto de hostilidad del empleador que faculta al trabajador para resolver el contrato de trabajo con aplicacion del articulo 166 N° 6 del Codigo del Trabajo. TERCERO: Que se declara aplicable al actor la opcion indemnizatoria prevista en el articulo 168 bis del Codigo del Trabajo. CUARTO: Que se declara que el trabajador no tuvo responsabilidad alguna en el termino de su relacion laboral. QUINTO: Que se condena a la demandada al pago al actor de las siguientes prestaciones: a) Indemnizacion sustitutiva del aviso previo; b) Indemnizacion por anos de servicio; c) Proporcional de vacaciones; d) Proporcional de feriado legal; e) Gratificacion proporcional; f) Ahorro previsional voluntario.",
    extracto: "Exigir al trabajador que continuara conduciendo pese a tener sintomas de COVID-19 y sin entregar implementos de proteccion constituye acto de hostilidad del empleador (Art. 166 N° 6 CT) que faculta la resolucion del contrato con opcion indemnizatoria.",
    fallo: "Se declara fundada la demanda. Se declara despido indirecto por hostilidad. Se aplica opcion indemnizatoria del Art. 168 bis CT.",
    fundamento: "Art. 166 N° 6 del Codigo del Trabajo. Exigencia de trabajo pese a enfermedad contagiosa sin proteccion. Falta grave de deberes de higiene y seguridad. Art. 168 bis CT opcion indemnizatoria.",
    normasAplicadas: "Art. 166 N° 6 CT, Art. 168 bis CT",
    fechaSentencia: "2022-11-10",
  },
  {
    rit: "C-6.444-2022",
    ruc: "",
    caratula: "Gonzalez v/s Walmart Chile S.A.",
    tribunal: "1° Juzgado de Letras del Trabajo de San Bernardo",
    tipo: "sentencia",
    materia: "laboral",
    contenido: "SENTENCIA. ROL C-6.444-2022. En la causa GONZALEZ v/s WALMART CHILE S.A., el 1° Juzgado de Letras del Trabajo de San Bernardo, en autos seguidos a pedido de DON CLAUDIO ALEJANDRO GONZALEZ TAPIA con WALMART CHILE S.A., sobre TUTELA DE DERECHOS, en sentencia de fecha 15 de noviembre de 2022, declaro: PRIMERO: Que se acoge la demanda. SEGUNDO: Que se declara que el despido del accionante se ampara en las necesidades de la empresa, razonamiento que se funda en el reordenamiento de locales, proyeccion de una nueva estructura jerarquica y redistribucion de funciones. TERCERO: Que se declara aplicable al recurrente el tope maximo previsto en el articulo 163 del Codigo del Trabajo. CUARTO: Se condena a la demandada al pago de: a) Indemnizacion sustitutiva del aviso previo; b) Indemnizacion por anos de servicio; c) Proporcional de vacaciones; d) Proporcional de feriado legal; e) Gratificacion proporcional.",
    extracto: "El reordenamiento de locales, proyeccion de nueva estructura jerarquica y redistribucion de funciones constituyen necesidades de la empresa validas para el despido (Art. 159 N° 6 CT). Se aplica tope de 330 dias.",
    fallo: "Se acoge demanda. Se declara despido por necesidades de la empresa por reordenamiento y redistribucion de funciones. Se aplica tope 330 dias.",
    fundamento: "Art. 159 N° 6° CT, Art. 163 CT. Reordenamiento de locales, nueva estructura jerarquica, redistribucion de funciones como necesidades de la empresa. Acreditacion de la causal.",
    normasAplicadas: "Art. 159 N° 6° CT, Art. 163 CT",
    fechaSentencia: "2022-11-15",
  },
  {
    rit: "C-15.896-2021",
    ruc: "",
    caratula: "Mujica v/s AFP Habitat S.A.",
    tribunal: "4° Juzgado de Letras del Trabajo de Santiago",
    tipo: "sentencia",
    materia: "laboral",
    contenido: "SENTENCIA. ROL C-15.896-2021. En la causa MUJICA v/s AFP HABITAT S.A., el 4° Juzgado de Letras del Trabajo de Santiago, en autos seguidos a pedido de DON LUIS ENRIQUE MUJICA MORALES con AFP HABITAT S.A., sobre TUTELA DE DERECHOS, en sentencia de fecha 16 de mayo de 2022, declaro: PRIMERO: Que se declara fundada la demanda. SEGUNDO: Que se declara que el actuar de la demandada, al desconocer sistematicamente el derecho a la desconexion digital del actor y exigirle permanentemente que respondiera a requerimientos laborales una vez terminada su jornada ordinaria, configura un incumplimiento grave de sus obligaciones. TERCERO: Que se declara aplicable al actor la opcion indemnizatoria del articulo 168 bis del Codigo del Trabajo. CUARTO: Que se condena a la AFP Habitat al pago de: a) Indemnizacion sustitutiva del aviso previo; b) Indemnizacion por anos de servicio; c) Proporcional de vacaciones; d) Proporcional de feriado legal; e) Gratificacion proporcional; f) Ahorro previsional voluntario.",
    extracto: "El desconocimiento sistematico del derecho a la desconexion digital y la exigencia permanente de respuesta fuera de jornada configura incumplimiento grave de obligaciones del empleador, dando derecho a la opcion indemnizatoria (Art. 168 bis CT).",
    fallo: "Se declara fundada la demanda. Se declara despido indirecto por incumplimiento grave. Se aplica opcion indemnizatoria del Art. 168 bis CT.",
    fundamento: "Art. 166 N° 6 y 7 CT (incumplimiento grave), Art. 184 bis CT (desconexion digital), Art. 168 bis CT (opcion indemnizatoria). Desconocimiento sistematico del derecho a desconexion digital.",
    normasAplicadas: "Art. 166 N° 6 y 7 CT, Art. 184 bis CT, Art. 168 bis CT",
    fechaSentencia: "2022-05-16",
  },
  {
    rit: "C-24.404-2020",
    ruc: "",
    caratula: "Caceres v/s Falabella Retail S.A.",
    tribunal: "7° Juzgado de Letras del Trabajo de Santiago",
    tipo: "sentencia",
    materia: "laboral",
    contenido: "SENTENCIA. ROL C-24.404-2020. En la causa CACERES v/s FALABELLA RETAIL S.A., el 7° Juzgado de Letras del Trabajo de Santiago, en autos seguidos a pedido de DON HECTOR FABIAN CACERES MARTINEZ con FALABELLA RETAIL S.A., sobre TUTELA DE DERECHOS, en sentencia de fecha 27 de julio de 2022, declaro: PRIMERO: Que se declara fundada la demanda. SEGUNDO: Que se declara que la causal invocada por la demandada -consistente en una reestructuracion y redimensionamiento de la fuerza de ventas- se encuentra acreditada. TERCERO: Que se declara aplicable al recurrente el tope maximo previsto en el articulo 163 del Codigo del Trabajo. CUARTO: Que se condena a Falabella Retail S.A. al pago de: a) Indemnizacion sustitutiva del aviso previo; b) Indemnizacion por anos de servicio; c) Proporcional de vacaciones; d) Proporcional de feriado legal; e) Gratificacion proporcional.",
    extracto: "La reestructuracion y redimensionamiento de la fuerza de ventas constituyen necesidades de la empresa validas (Art. 159 N° 6 CT). Se aplica el tope de 330 dias de remuneracion.",
    fallo: "Se declara fundada la demanda. Se declara despido por necesidades de la empresa por reestructuracion. Se aplica tope 330 dias.",
    fundamento: "Art. 159 N° 6° CT, Art. 163 CT. Reestructuracion y redimensionamiento de fuerza de ventas. Acreditacion documental de la causal.",
    normasAplicadas: "Art. 159 N° 6° CT, Art. 163 CT",
    fechaSentencia: "2022-07-27",
  },
  {
    rit: "C-22.950-2020",
    ruc: "",
    caratula: "Lagos v/s Cencosud Retail S.A.",
    tribunal: "7° Juzgado de Letras del Trabajo de Santiago",
    tipo: "sentencia",
    materia: "laboral",
    contenido: "SENTENCIA. ROL C-22.950-2020. En la causa LAGOS v/s CENCOSUD RETAIL S.A., el 7° Juzgado de Letras del Trabajo de Santiago, en autos seguidos a pedido de DON RONALD ALEJANDRO LAGOS SANCHEZ con CENCOSUD RETAIL S.A., sobre TUTELA DE DERECHOS, en sentencia de fecha 30 de agosto de 2022, declaro: PRIMERO: Que se declara fundada la demanda. SEGUNDO: Que se declara que el despido del actor se encuentra amparado en la causal de necesidades de la empresa, especificamente el cierre de la unidad de negocio en la cual trabajaba el actor. TERCERO: Que se declara aplicable al actor el tope maximo del Art. 163 CT. CUARTO: Que se condena a Cencosud Retail S.A. al pago de: a) Indemnizacion sustitutiva del aviso previo; b) Indemnizacion por anos de servicio; c) Proporcional de vacaciones; d) Proporcional de feriado legal.",
    extracto: "El cierre de la unidad de negocio donde trabajaba el actor constituye necesidad de la empresa valida (Art. 159 N° 6 CT). El cierre debe ser real y no simulado.",
    fallo: "Se declara fundada la demanda. Se declara despido por necesidades de la empresa por cierre de unidad. Se aplica tope 330 dias.",
    fundamento: "Art. 159 N° 6° CT, Art. 163 CT. Cierre de unidad de negocio. Acreditacion fehaciente del cierre.",
    normasAplicadas: "Art. 159 N° 6° CT, Art. 163 CT",
    fechaSentencia: "2022-08-30",
  },
  {
    rit: "C-15.012-2022",
    ruc: "",
    caratula: "Vergara v/s Claro Chile S.A.",
    tribunal: "12° Juzgado de Letras del Trabajo de Santiago",
    tipo: "sentencia",
    materia: "laboral",
    contenido: "SENTENCIA. ROL C-15.012-2022. En la causa VERGARA v/s CLARO CHILE S.A., el 12° Juzgado de Letras del Trabajo de Santiago, en autos seguidos a pedido de DON MARCELO ALBERTO VERGARA DIAZ con CLARO CHILE S.A., sobre TUTELA DE DERECHOS, en sentencia de fecha 24 de noviembre de 2022, declaro: PRIMERO: Que se declara fundada la demanda. SEGUNDO: Que se declara que la causal invocada por la demandada, relativa a una reestructuracion organizacional, se encuentra debidamente acreditada. TERCERO: Que se declara aplicable al actor el tope maximo del Art. 163 CT. CUARTO: Que se condena a Claro Chile S.A. al pago de: a) Indemnizacion sustitutiva del aviso previo; b) Indemnizacion por anos de servicio; c) Proporcional de vacaciones; d) Proporcional de feriado legal; e) Gratificacion proporcional.",
    extracto: "La reestructuracion organizacional debidamente acreditada constituye necesidad de la empresa valida para el despido (Art. 159 N° 6 CT). Se aplica tope de 330 dias.",
    fallo: "Se declara fundada. Se declara despido por necesidades de la empresa por reestructuracion organizacional. Se aplica tope 330 dias.",
    fundamento: "Art. 159 N° 6° CT, Art. 163 CT. Reestructuracion organizacional. Acreditacion mediante documentos internos.",
    normasAplicadas: "Art. 159 N° 6° CT, Art. 163 CT",
    fechaSentencia: "2022-11-24",
  },
  {
    rit: "C-2.215-2022",
    ruc: "",
    caratula: "Gonzalez v/s Servicios de Asesoria y Administracion Gestion Humana Limitada",
    tribunal: "2° Juzgado de Letras del Trabajo de Santiago",
    tipo: "sentencia",
    materia: "laboral",
    contenido: "SENTENCIA. ROL C-2.215-2022. En la causa GONZALEZ v/s SERVICIOS DE ASESORIA Y ADMINISTRACION GESTION HUMANA LIMITADA, el 2° Juzgado de Letras del Trabajo de Santiago, en autos seguidos a pedido de DON FELIPE GONZALEZ ROJAS con SERVICIOS DE ASESORIA Y ADMINISTRACION GESTION HUMANA LIMITADA, sobre TUTELA DE DERECHOS, en sentencia de fecha 30 de noviembre de 2022, declaro: PRIMERO: Que se declara fundada la demanda. SEGUNDO: Que se declara que la causal invocada por la demandada, relativa a una reestructuracion organizacional, se encuentra debidamente acreditada. TERCERO: Que se declara aplicable al actor el tope maximo del Art. 163 CT. CUARTO: Que se condena al pago de: a) Indemnizacion sustitutiva del aviso previo; b) Indemnizacion por anos de servicio; c) Proporcional de vacaciones; d) Proporcional de feriado legal.",
    extracto: "La reestructuracion organizacional acreditada documentalmente constituye necesidad de la empresa. Se aplica tope maximo de 330 dias de remuneracion.",
    fallo: "Se declara fundada. Se declara despido por necesidades de la empresa. Se aplica tope 330 dias.",
    fundamento: "Art. 159 N° 6° CT, Art. 163 CT. Reestructuracion organizacional acreditada.",
    normasAplicadas: "Art. 159 N° 6° CT, Art. 163 CT",
    fechaSentencia: "2022-11-30",
  },
];
