import {
  expedientes,
  causas,
  tareas,
  alertas,
  cronologia,
  notas,
  honorarios,
  leykarinDenuncias,
  leykarinActuaciones,
  diarioOficialNormas,
} from "@db/schema";

// ====================================================================
// SEED SERVICIOS COMPLETOS - DATOS REALISTAS DERECHO LABORAL CHILENO
// Pobla todas las tablas operacionales para que los agentes funcionen
// ====================================================================

export async function seedServiciosCompletos(db: any) {
  console.log("\n[SC] Insertando datos de servicios completos...");

  // ─── 1. EXPEDIENTES ──────────────────────────────────────────────
  console.log("  [1/10] Expedientes...");
  const expedientesData = await db.insert(expedientes).values([
    {
      codigo: "EXP-2025-001",
      nombre: "Despido Injustificado - Martínez Rojas",
      descripcion: "Demanda por despido injustificado y cobro de prestaciones laborales adeudadas. Cliente despedido sin carta de aviso.",
      materia: "laboral" as const,
      estado: "activo" as const,
      prioridad: "alta" as const,
      cliente: "Roberto Martínez Rojas",
      clienteRut: "12.345.678-9",
      abogadoAsignado: "Valentina Herrera Soto",
      asistenteAsignado: "Diego Castillo Muñoz",
      tribunal: "1° Juzgado de Letras del Trabajo de Santiago",
      fechaInicio: "2025-02-10",
      fechaEstimadaCierre: "2026-08-30",
    },
    {
      codigo: "EXP-2025-002",
      nombre: "Tutela de Derechos Fundamentales - Vargas Flores",
      descripcion: "Vulneración de derechos fundamentales: discriminación por embarazo y acoso laboral por parte de jefe directo.",
      materia: "laboral" as const,
      estado: "activo" as const,
      prioridad: "critica" as const,
      cliente: "Claudia Vargas Flores",
      clienteRut: "15.678.234-5",
      abogadoAsignado: "Valentina Herrera Soto",
      asistenteAsignado: "Diego Castillo Muñoz",
      tribunal: "2° Juzgado de Letras del Trabajo de Santiago",
      fechaInicio: "2025-03-15",
      fechaEstimadaCierre: "2026-06-15",
    },
    {
      codigo: "EXP-2025-003",
      nombre: "Cobro de Cotizaciones Previsionales - Pérez Nahuelqui",
      descripcion: "Cobro de cotizaciones previsionales no enteradas por empleador durante 3 años. AFP Provida informa deuda.",
      materia: "laboral" as const,
      estado: "activo" as const,
      prioridad: "media" as const,
      cliente: "Luis Pérez Nahuelqui",
      clienteRut: "8.901.234-6",
      abogadoAsignado: "Sebastián Moya Lagos",
      asistenteAsignado: "Diego Castillo Muñoz",
      tribunal: "Juzgado de Letras del Trabajo de Concepción",
      fechaInicio: "2025-01-20",
      fechaEstimadaCierre: "2026-04-30",
    },
    {
      codigo: "EXP-2024-047",
      nombre: "Accidente del Trabajo - Fernández Contreras",
      descripcion: "Demanda de indemnización de perjuicios por accidente del trabajo que produjo incapacidad permanente parcial. Empresa no tenía protocolo de seguridad.",
      materia: "laboral" as const,
      estado: "activo" as const,
      prioridad: "alta" as const,
      cliente: "Manuel Fernández Contreras",
      clienteRut: "11.234.567-K",
      abogadoAsignado: "Valentina Herrera Soto",
      asistenteAsignado: "María José Reyes Alvarado",
      tribunal: "Juzgado de Letras del Trabajo de Valparaíso",
      fechaInicio: "2024-09-05",
      fechaEstimadaCierre: "2026-09-05",
    },
    {
      codigo: "EXP-2024-031",
      nombre: "Nulidad de Despido - Torres Iturra (Concluido)",
      descripcion: "Nulidad de despido por no pago de cotizaciones previsionales al momento del finiquito. Causa concluida con sentencia favorable.",
      materia: "laboral" as const,
      estado: "concluido" as const,
      prioridad: "baja" as const,
      cliente: "Ana Torres Iturra",
      clienteRut: "14.567.890-3",
      abogadoAsignado: "Sebastián Moya Lagos",
      asistenteAsignado: "María José Reyes Alvarado",
      tribunal: "3° Juzgado de Letras del Trabajo de Santiago",
      fechaInicio: "2024-03-01",
      fechaEstimadaCierre: "2025-03-01",
    },
  ] as any).$returningId();

  const expIds = expedientesData.map((e: { id: number }) => e.id);

  // ─── 2. CAUSAS ───────────────────────────────────────────────────
  console.log("  [2/10] Causas...");
  const causasData = await db.insert(causas).values([
    {
      rit: "T-234-2025",
      ruc: "C-12345-2025-LAB",
      caratula: "Martínez Rojas, Roberto c/ Servicios Industriales del Sur Ltda.",
      tribunal: "1° Juzgado de Letras del Trabajo de Santiago",
      comuna: "Santiago",
      region: "Región Metropolitana",
      materia: "laboral" as const,
      estado: "tramitacion" as const,
      etapa: "Audiencia preparatoria",
      fechaIngreso: "2025-02-10",
      fechaUltimoMovimiento: "2025-05-10",
      litigantes: "Demandante: Roberto Martínez Rojas (RUT 12.345.678-9) | Demandado: Servicios Industriales del Sur Ltda. (RUT 76.123.456-7)",
      abogadoDemandante: "Valentina Herrera Soto",
      abogadoDemandado: "Rodrigo Pinto Araya",
      expedienteId: expIds[0],
      estaMonitoreando: true,
      fuente: "consulta_unificada" as const,
    },
    {
      rit: "T-089-2025",
      ruc: "C-67890-2025-LAB",
      caratula: "Vargas Flores, Claudia c/ Comercial Andina S.A.",
      tribunal: "2° Juzgado de Letras del Trabajo de Santiago",
      comuna: "Santiago",
      region: "Región Metropolitana",
      materia: "laboral" as const,
      estado: "prueba" as const,
      etapa: "Período de prueba testimonial",
      fechaIngreso: "2025-03-15",
      fechaUltimoMovimiento: "2025-05-18",
      litigantes: "Demandante: Claudia Vargas Flores (RUT 15.678.234-5) | Demandado: Comercial Andina S.A. (RUT 96.789.012-3)",
      abogadoDemandante: "Valentina Herrera Soto",
      abogadoDemandado: "Carmen Salinas Vidal",
      expedienteId: expIds[1],
      estaMonitoreando: true,
      fuente: "consulta_unificada" as const,
    },
    {
      rit: "C-456-2025",
      ruc: "C-34567-2025-LAB",
      caratula: "Pérez Nahuelqui, Luis c/ Constructora Los Andes S.A.",
      tribunal: "Juzgado de Letras del Trabajo de Concepción",
      comuna: "Concepción",
      region: "Biobío",
      materia: "laboral" as const,
      estado: "tramitacion" as const,
      etapa: "Notificación al demandado",
      fechaIngreso: "2025-01-20",
      fechaUltimoMovimiento: "2025-04-25",
      litigantes: "Demandante: Luis Pérez Nahuelqui (RUT 8.901.234-6) | Demandado: Constructora Los Andes S.A. (RUT 88.234.567-1)",
      abogadoDemandante: "Sebastián Moya Lagos",
      abogadoDemandado: "Sin abogado designado",
      expedienteId: expIds[2],
      estaMonitoreando: true,
      fuente: "consulta_unificada" as const,
    },
    {
      rit: "O-178-2024",
      ruc: "C-89012-2024-LAB",
      caratula: "Fernández Contreras, Manuel c/ Minera Austral SpA",
      tribunal: "Juzgado de Letras del Trabajo de Valparaíso",
      comuna: "Valparaíso",
      region: "Valparaíso",
      materia: "laboral" as const,
      estado: "sentencia" as const,
      etapa: "En estado de acuerdo - Sentencia definitiva",
      fechaIngreso: "2024-09-05",
      fechaUltimoMovimiento: "2026-05-15",
      litigantes: "Demandante: Manuel Fernández Contreras (RUT 11.234.567-K) | Demandado: Minera Austral SpA (RUT 77.345.678-2)",
      abogadoDemandante: "Valentina Herrera Soto",
      abogadoDemandado: "Pedro Morales Escobar",
      expedienteId: expIds[3],
      estaMonitoreando: true,
      fuente: "consulta_unificada" as const,
    },
    {
      rit: "T-512-2024",
      ruc: "C-56789-2024-LAB",
      caratula: "Torres Iturra, Ana c/ Retail Patagonia Ltda.",
      tribunal: "3° Juzgado de Letras del Trabajo de Santiago",
      comuna: "Providencia",
      region: "Región Metropolitana",
      materia: "laboral" as const,
      estado: "concluida" as const,
      etapa: "Sentencia ejecutoriada",
      fechaIngreso: "2024-03-01",
      fechaUltimoMovimiento: "2025-02-28",
      litigantes: "Demandante: Ana Torres Iturra (RUT 14.567.890-3) | Demandado: Retail Patagonia Ltda. (RUT 79.456.789-4)",
      abogadoDemandante: "Sebastián Moya Lagos",
      abogadoDemandado: "Jorge Álvarez Campos",
      expedienteId: expIds[4],
      estaMonitoreando: false,
      fuente: "consulta_unificada" as const,
    },
    {
      rit: "M-045-2026",
      ruc: "C-11223-2026-LAB",
      caratula: "Sanhueza Bravo, Patricia c/ Clínica Bío Bío S.A.",
      tribunal: "Juzgado de Letras del Trabajo de Temuco",
      comuna: "Temuco",
      region: "La Araucanía",
      materia: "laboral" as const,
      estado: "notificacion" as const,
      etapa: "Pendiente notificación personal al demandado",
      fechaIngreso: "2026-04-08",
      fechaUltimoMovimiento: "2026-05-05",
      litigantes: "Demandante: Patricia Sanhueza Bravo (RUT 17.890.123-7) | Demandado: Clínica Bío Bío S.A. (RUT 91.567.890-5)",
      abogadoDemandante: "Valentina Herrera Soto",
      abogadoDemandado: "Sin abogado designado",
      expedienteId: null,
      estaMonitoreando: true,
      fuente: "consulta_unificada" as const,
    },
    {
      rit: "T-321-2025",
      ruc: "C-44556-2025-LAB",
      caratula: "Jara Sepúlveda, Carlos c/ Empresa de Seguridad Guardex Ltda.",
      tribunal: "Juzgado de Letras del Trabajo de Antofagasta",
      comuna: "Antofagasta",
      region: "Antofagasta",
      materia: "laboral" as const,
      estado: "ejecucion" as const,
      etapa: "Cumplimiento de sentencia - Embargo de bienes",
      fechaIngreso: "2025-07-14",
      fechaUltimoMovimiento: "2026-04-20",
      litigantes: "Demandante: Carlos Jara Sepúlveda (RUT 9.876.543-2) | Demandado: Empresa de Seguridad Guardex Ltda. (RUT 85.678.901-6)",
      abogadoDemandante: "Sebastián Moya Lagos",
      abogadoDemandado: "Luis Fernández Ríos",
      expedienteId: null,
      estaMonitoreando: true,
      fuente: "consulta_unificada" as const,
    },
    {
      rit: "T-199-2026",
      ruc: "C-77889-2026-LAB",
      caratula: "Molina Espinoza, Jorge c/ Laboratorio Farma Chile S.A.",
      tribunal: "1° Juzgado de Letras del Trabajo de Santiago",
      comuna: "Las Condes",
      region: "Región Metropolitana",
      materia: "laboral" as const,
      estado: "archivada" as const,
      etapa: "Archivada por abandono del procedimiento",
      fechaIngreso: "2026-01-15",
      fechaUltimoMovimiento: "2026-03-15",
      litigantes: "Demandante: Jorge Molina Espinoza (RUT 13.456.789-0) | Demandado: Laboratorio Farma Chile S.A. (RUT 92.345.678-8)",
      abogadoDemandante: "Valentina Herrera Soto",
      abogadoDemandado: "Patricia Vidal Rojas",
      expedienteId: null,
      estaMonitoreando: false,
      fuente: "consulta_unificada" as const,
    },
  ] as any).$returningId();

  const causaIds = causasData.map((c: { id: number }) => c.id);

  // ─── 3. TAREAS ───────────────────────────────────────────────────
  console.log("  [3/10] Tareas...");
  await db.insert(tareas).values([
    {
      titulo: "Revisar contestación demanda C-456",
      descripcion: "Revisar contestación presentada por Constructora Los Andes S.A. y elaborar estrategia de réplica.",
      causaId: causaIds[2],
      expedienteId: expIds[2],
      asignadoA: "Valentina Herrera Soto",
      creadoPor: "Valentina Herrera Soto",
      tipo: "revision_documento" as const,
      estado: "pendiente" as const,
      prioridad: "alta" as const,
      fechaVencimiento: "2026-05-28",
      notas: "Priorizar análisis de excepción de prescripción planteada por demandado",
      etiquetas: "contestacion,prescripcion,urgent",
    },
    {
      titulo: "Preparar recurso de nulidad T-512-2024",
      descripcion: "Redactar recurso de nulidad contra sentencia desfavorable en causa Torres Iturra. Plazo fatal 10 días hábiles.",
      causaId: causaIds[4],
      expedienteId: expIds[4],
      asignadoA: "Sebastián Moya Lagos",
      creadoPor: "Valentina Herrera Soto",
      tipo: "preparar_escrito" as const,
      estado: "en_progreso" as const,
      prioridad: "critica" as const,
      fechaVencimiento: "2026-05-27",
      notas: "Causal: infracción ley en la decisión - Art. 477 CT",
      etiquetas: "nulidad,plazo_fatal,recurso",
    },
    {
      titulo: "Notificar cliente resultado audiencia T-089-2025",
      descripcion: "Informar a Claudia Vargas Flores el resultado de la audiencia de prueba del 18 de mayo.",
      causaId: causaIds[1],
      expedienteId: expIds[1],
      asignadoA: "Diego Castillo Muñoz",
      creadoPor: "Valentina Herrera Soto",
      tipo: "notificar_cliente" as const,
      estado: "completada" as const,
      prioridad: "media" as const,
      fechaVencimiento: "2026-05-20",
      fechaCompletada: new Date("2026-05-19"),
      notas: "Cliente notificada. Próxima audiencia: 15 de junio.",
      etiquetas: "notificacion,cliente",
    },
    {
      titulo: "Seguimiento causa O-178-2024 - Sentencia pendiente",
      descripcion: "Monitorear ingreso de sentencia definitiva en causa Fernández Contreras. Se esperaba para el 20 de mayo.",
      causaId: causaIds[3],
      expedienteId: expIds[3],
      asignadoA: "Valentina Herrera Soto",
      creadoPor: "Valentina Herrera Soto",
      tipo: "seguimiento_causa" as const,
      estado: "en_progreso" as const,
      prioridad: "alta" as const,
      fechaVencimiento: "2026-05-31",
      notas: "Consultar PJUD cada 2 días",
      etiquetas: "sentencia,seguimiento",
    },
    {
      titulo: "Revisar resolución N°45 en T-234-2025",
      descripcion: "Revisar resolución que fija fecha de audiencia preparatoria y determinar si procede recurso de reposición.",
      causaId: causaIds[0],
      expedienteId: expIds[0],
      asignadoA: "Valentina Herrera Soto",
      creadoPor: "Diego Castillo Muñoz",
      tipo: "revisar_resolucion" as const,
      estado: "pendiente" as const,
      prioridad: "alta" as const,
      fechaVencimiento: "2026-05-29",
      notas: "Analizar si la fecha fijada es conforme al art. 451 CT",
      etiquetas: "resolucion,audiencia_preparatoria",
    },
    {
      titulo: "Checklist finiquito - Martínez Rojas",
      descripcion: "Verificar todos los ítems del finiquito presentado por la contraparte en audiencia de conciliación.",
      causaId: causaIds[0],
      expedienteId: expIds[0],
      asignadoA: "Diego Castillo Muñoz",
      creadoPor: "Valentina Herrera Soto",
      tipo: "checklist_finiquito" as const,
      estado: "pendiente" as const,
      prioridad: "media" as const,
      fechaVencimiento: "2026-06-05",
      notas: "Verificar cálculo de indemnización y cotizaciones",
      etiquetas: "finiquito,checklist",
    },
    {
      titulo: "Agendar audiencia de conciliación M-045-2026",
      descripcion: "Coordinar con tribunal y cliente fecha de audiencia de conciliación una vez notificado el demandado.",
      causaId: causaIds[5],
      expedienteId: null,
      asignadoA: "Diego Castillo Muñoz",
      creadoPor: "Valentina Herrera Soto",
      tipo: "agendar_audiencia" as const,
      estado: "pendiente" as const,
      prioridad: "media" as const,
      fechaVencimiento: "2026-06-15",
      notas: "Confirmar notificación antes de agendar",
      etiquetas: "audiencia,conciliacion",
    },
    {
      titulo: "Investigar normativa sobre subcontratación - cliente Construcción",
      descripcion: "Investigar alcance de la responsabilidad solidaria en caso de empresa contratista y subcontratista.",
      causaId: null,
      expedienteId: expIds[2],
      asignadoA: "Sebastián Moya Lagos",
      creadoPor: "Valentina Herrera Soto",
      tipo: "investigar_norma" as const,
      estado: "completada" as const,
      prioridad: "baja" as const,
      fechaVencimiento: "2026-05-10",
      fechaCompletada: new Date("2026-05-09"),
      notas: "Art. 183-A y ss. CT. Responsabilidad solidaria verificada.",
      etiquetas: "subcontratacion,investigacion,art183",
    },
    {
      titulo: "Revisar Diario Oficial - Normas laborales semana 22/05",
      descripcion: "Revisar edición del Diario Oficial del 22 al 26 de mayo de 2026 para detectar cambios normativos laborales.",
      causaId: null,
      expedienteId: null,
      asignadoA: "Diego Castillo Muñoz",
      creadoPor: "Sistema LexTrack",
      tipo: "revisar_diario_oficial" as const,
      estado: "pendiente" as const,
      prioridad: "baja" as const,
      fechaVencimiento: "2026-05-26",
      notas: "Atención especial a normas DT y MINTRAB",
      etiquetas: "diario_oficial,normas,semana",
    },
    {
      titulo: "Preparar escrito de observaciones a prueba T-089-2025",
      descripcion: "Redactar escrito de observaciones a la prueba presentada por Comercial Andina S.A. Plazo 5 días hábiles.",
      causaId: causaIds[1],
      expedienteId: expIds[1],
      asignadoA: "Valentina Herrera Soto",
      creadoPor: "Valentina Herrera Soto",
      tipo: "preparar_escrito" as const,
      estado: "pendiente" as const,
      prioridad: "alta" as const,
      fechaVencimiento: "2026-05-28",
      notas: "Impugnar testigos no declararon sobre los hechos directamente",
      etiquetas: "escrito,observaciones_prueba,tutela",
    },
    {
      titulo: "Verificar pago cotizaciones previsionales - Pérez Nahuelqui OVERDUE",
      descripcion: "Verificar estado de cotizaciones en AFP Provida y Fonasa para período 2022-2024. TAREA VENCIDA.",
      causaId: causaIds[2],
      expedienteId: expIds[2],
      asignadoA: "Diego Castillo Muñoz",
      creadoPor: "Sebastián Moya Lagos",
      tipo: "revision_documento" as const,
      estado: "pendiente" as const,
      prioridad: "alta" as const,
      fechaVencimiento: "2026-05-15",
      notas: "VENCIDA - Pendiente de completar",
      etiquetas: "cotizaciones,afp,vencida,overdue",
    },
    {
      titulo: "Checklist despido procedente - análisis factual T-321-2025",
      descripcion: "Verificar si procedimientos disciplinarios fueron aplicados correctamente antes del despido. Revisión expediente interno.",
      causaId: causaIds[6],
      expedienteId: null,
      asignadoA: "Sebastián Moya Lagos",
      creadoPor: "Valentina Herrera Soto",
      tipo: "checklist_despido" as const,
      estado: "pendiente" as const,
      prioridad: "media" as const,
      fechaVencimiento: "2026-05-20",
      notas: "Empresa en etapa de cumplimiento - revisar si acogerse a acuerdo",
      etiquetas: "despido,checklist,ejecucion",
    },
    {
      titulo: "Informe de gestión mensual - Mayo 2026",
      descripcion: "Preparar informe de gestión mensual con resumen de causas activas, vencimientos próximos y estados.",
      causaId: null,
      expedienteId: null,
      asignadoA: "Valentina Herrera Soto",
      creadoPor: "Sistema LexTrack",
      tipo: "otra" as const,
      estado: "pendiente" as const,
      prioridad: "baja" as const,
      fechaVencimiento: "2026-05-31",
      notas: "Entregar a dirección el 31 de mayo",
      etiquetas: "informe,gestion,mensual",
    },
    {
      titulo: "Revisar documental demanda O-178-2024 - Peritos",
      descripcion: "Revisar informe pericial de médico laboral sobre incapacidad permanente parcial de Manuel Fernández.",
      causaId: causaIds[3],
      expedienteId: expIds[3],
      asignadoA: "Valentina Herrera Soto",
      creadoPor: "Valentina Herrera Soto",
      tipo: "revision_documento" as const,
      estado: "completada" as const,
      prioridad: "critica" as const,
      fechaVencimiento: "2026-05-12",
      fechaCompletada: new Date("2026-05-11"),
      notas: "Informe pericial confirma 40% de incapacidad. Muy favorable.",
      etiquetas: "peritaje,accidente_trabajo,incapacidad",
    },
    {
      titulo: "Preparar alegatos finales T-089-2025",
      descripcion: "Redactar alegatos para audiencia de cierre del 15 de junio. Énfasis en discriminación por embarazo.",
      causaId: causaIds[1],
      expedienteId: expIds[1],
      asignadoA: "Valentina Herrera Soto",
      creadoPor: "Valentina Herrera Soto",
      tipo: "preparar_escrito" as const,
      estado: "pendiente" as const,
      prioridad: "alta" as const,
      fechaVencimiento: "2026-06-13",
      notas: "Citar jurisprudencia reciente CS en casos de tutela y embarazo",
      etiquetas: "alegatos,tutela,embarazo,cierre",
    },
  ] as any);

  // ─── 4. ALERTAS ──────────────────────────────────────────────────
  console.log("  [4/10] Alertas...");
  await db.insert(alertas).values([
    {
      causaId: causaIds[1],
      expedienteId: expIds[1],
      tipo: "prazo_proximo" as const,
      titulo: "Plazo próximo: Escrito observaciones prueba T-089-2025",
      descripcion: "Plazo para presentar escrito de observaciones a la prueba vence el 28 de mayo. Quedan 2 días hábiles.",
      prioridad: "critica" as const,
      estado: "pendiente" as const,
      fechaEvento: "2026-05-18",
      fechaVencimiento: "2026-05-28",
      metadata: { diasRestantes: 2, tipo_plazo: "procesal", articulo: "Art. 454 CT" },
    },
    {
      causaId: causaIds[1],
      expedienteId: expIds[1],
      tipo: "audiencia_programada" as const,
      titulo: "Audiencia de cierre T-089-2025 - 15 de junio",
      descripcion: "Audiencia de cierre y alegatos programada para el 15 de junio de 2026 a las 10:30 hrs. Tribunal 2° JLT Santiago.",
      prioridad: "alta" as const,
      estado: "pendiente" as const,
      fechaEvento: "2026-06-15",
      fechaVencimiento: "2026-06-14",
      metadata: { hora: "10:30", sala: "3", tipo_audiencia: "cierre" },
    },
    {
      causaId: causaIds[3],
      expedienteId: expIds[3],
      tipo: "cambio_estado" as const,
      titulo: "Causa O-178-2024 en estado de acuerdo - Sentencia próxima",
      descripcion: "La causa Fernández Contreras c/ Minera Austral entró en estado de acuerdo el 15 de mayo. Sentencia esperada en 30 días.",
      prioridad: "alta" as const,
      estado: "pendiente" as const,
      fechaEvento: "2026-05-15",
      fechaVencimiento: "2026-06-15",
      metadata: { estado_anterior: "prueba", estado_nuevo: "sentencia", dias_para_sentencia: 30 },
    },
    {
      causaId: causaIds[0],
      expedienteId: expIds[0],
      tipo: "audiencia_programada" as const,
      titulo: "Audiencia preparatoria T-234-2025 - 5 de junio",
      descripcion: "Audiencia preparatoria fijada para el 5 de junio de 2026 a las 09:00 hrs. Preparar documentos probatorios.",
      prioridad: "alta" as const,
      estado: "pendiente" as const,
      fechaEvento: "2026-06-05",
      fechaVencimiento: "2026-06-04",
      metadata: { hora: "09:00", sala: "7", tipo_audiencia: "preparatoria" },
    },
    {
      causaId: causaIds[2],
      expedienteId: expIds[2],
      tipo: "prazo_proximo" as const,
      titulo: "Verificación cotizaciones previsionales VENCIDA - C-456",
      descripcion: "Tarea de verificación de cotizaciones previsionales venció el 15 de mayo. Requiere atención inmediata.",
      prioridad: "critica" as const,
      estado: "pendiente" as const,
      fechaEvento: "2026-05-15",
      fechaVencimiento: "2026-05-15",
      metadata: { dias_vencida: 11, accion_requerida: "completar_verificacion_cotizaciones" },
    },
    {
      causaId: null,
      expedienteId: null,
      tipo: "diario_oficial" as const,
      titulo: "Nueva norma laboral: Decreto 156-2026 sobre jornada adaptable",
      descripcion: "Publicado en Diario Oficial el 20 de mayo. Decreto modifica regulación de jornada laboral adaptable para empresas de hasta 50 trabajadores.",
      prioridad: "media" as const,
      estado: "pendiente" as const,
      fechaEvento: "2026-05-20",
      fechaVencimiento: "2026-06-20",
      metadata: { numero_norma: "156", tipo_norma: "decreto", materia: "jornada_adaptable" },
    },
    {
      causaId: null,
      expedienteId: null,
      tipo: "cambio_normativo" as const,
      titulo: "Actualización IMM - Ingreso Mínimo Mayo 2026",
      descripcion: "El Ingreso Mínimo Mensual fue actualizado a $550.000 según Decreto Supremo N°48 del MINTRAB. Vigencia desde 1 de mayo de 2026.",
      prioridad: "media" as const,
      estado: "leida" as const,
      fechaEvento: "2026-05-01",
      fechaVencimiento: null,
      leidaAt: new Date("2026-05-02"),
      metadata: { imm_nuevo: 550000, imm_anterior: 520000, vigencia: "2026-05-01" },
    },
    {
      causaId: causaIds[6],
      expedienteId: null,
      tipo: "cambio_estado" as const,
      titulo: "T-321-2025 en etapa de ejecución - Embargo en proceso",
      descripcion: "La causa Jara Sepúlveda entró en fase de ejecución. Se ordenó embargo de bienes de Guardex Ltda. Coordinar con receptor judicial.",
      prioridad: "alta" as const,
      estado: "pendiente" as const,
      fechaEvento: "2026-04-20",
      fechaVencimiento: "2026-06-20",
      metadata: { receptor_judicial: "Carlos Ibarra Soto", monto_embargo: 8500000 },
    },
    {
      causaId: causaIds[4],
      expedienteId: expIds[4],
      tipo: "prazo_proximo" as const,
      titulo: "Plazo para recurso de nulidad T-512-2024 vence el 27 mayo",
      descripcion: "Plazo fatal de 10 días hábiles para recurso de nulidad. Solo quedan 1 día hábil.",
      prioridad: "critica" as const,
      estado: "pendiente" as const,
      fechaEvento: "2026-05-13",
      fechaVencimiento: "2026-05-27",
      metadata: { dias_restantes: 1, tipo_recurso: "nulidad", articulo: "Art. 477 CT", es_plazo_fatal: true },
    },
    {
      causaId: null,
      expedienteId: null,
      tipo: "dt_dictamen" as const,
      titulo: "Nuevo dictamen DT N°1523/2026 sobre teletrabajo",
      descripcion: "Dirección del Trabajo emitió dictamen sobre obligaciones del empleador en teletrabajo: herramientas, conectividad y privacidad del trabajador.",
      prioridad: "baja" as const,
      estado: "archivada" as const,
      fechaEvento: "2026-05-10",
      fechaVencimiento: null,
      metadata: { numero_dictamen: "1523/2026", materia: "teletrabajo", url_dt: "https://www.dt.gob.cl/dictamenes" },
    },
  ] as any);

  // ─── 5. CRONOLOGIA ───────────────────────────────────────────────
  console.log("  [5/10] Cronología...");
  await db.insert(cronologia).values([
    {
      causaId: causaIds[0],
      expedienteId: expIds[0],
      fecha: "2025-02-10",
      hora: "09:15",
      tipo: "ingreso" as const,
      titulo: "Ingreso de demanda T-234-2025",
      descripcion: "Demanda de tutela de derechos fundamentales por despido injustificado. Presentada vía Oficina Judicial Virtual.",
      actor: "Valentina Herrera Soto",
      fuente: "pjud",
    },
    {
      causaId: causaIds[0],
      expedienteId: expIds[0],
      fecha: "2025-03-05",
      hora: "11:30",
      tipo: "notificacion" as const,
      titulo: "Notificación al demandado - T-234-2025",
      descripcion: "Notificación personal a Servicios Industriales del Sur Ltda. en su domicilio registrado. Notificó receptor judicial Daniel Vega.",
      actor: "Receptor Judicial Daniel Vega",
      fuente: "pjud",
    },
    {
      causaId: causaIds[0],
      expedienteId: expIds[0],
      fecha: "2025-04-15",
      hora: "10:00",
      tipo: "audiencia" as const,
      titulo: "Audiencia de conciliación T-234-2025",
      descripcion: "Audiencia de conciliación sin acuerdo. Demandado ofreció 3 meses de indemnización; demandante rechazó. Causa pasa a audiencia preparatoria.",
      actor: "Juez Patricio Villalobos Méndez",
      fuente: "pjud",
    },
    {
      causaId: causaIds[0],
      expedienteId: expIds[0],
      fecha: "2026-06-05",
      hora: "09:00",
      tipo: "audiencia" as const,
      titulo: "Audiencia preparatoria T-234-2025 - Fijada",
      descripcion: "Fecha fijada para audiencia preparatoria. Se requiere presentar lista de testigos y documentos probatorios con 5 días de anticipación.",
      actor: "Sistema Judicial",
      fuente: "pjud",
    },
    {
      causaId: causaIds[1],
      expedienteId: expIds[1],
      fecha: "2025-03-15",
      hora: "14:20",
      tipo: "ingreso" as const,
      titulo: "Ingreso demanda tutela T-089-2025",
      descripcion: "Demanda de tutela de derechos fundamentales por discriminación por embarazo y acoso laboral. Admitida a tramitación.",
      actor: "Valentina Herrera Soto",
      fuente: "pjud",
    },
    {
      causaId: causaIds[1],
      expedienteId: expIds[1],
      fecha: "2025-05-20",
      hora: "09:30",
      tipo: "audiencia" as const,
      titulo: "Audiencia preparatoria T-089-2025 - Prueba admitida",
      descripcion: "Se admitió prueba documental, testimonial (3 testigos) y pericial (informe psicológico). Período de prueba fijado para agosto.",
      actor: "Jueza Carolina Muñoz Flores",
      fuente: "pjud",
    },
    {
      causaId: causaIds[1],
      expedienteId: expIds[1],
      fecha: "2026-05-18",
      hora: "10:00",
      tipo: "prueba" as const,
      titulo: "Audiencia de prueba testimonial T-089-2025",
      descripcion: "Declararon testigos de la demandante. Testimonio de compañera de trabajo confirmó episodios de hostigamiento documentados.",
      actor: "Jueza Carolina Muñoz Flores",
      fuente: "pjud",
    },
    {
      causaId: causaIds[1],
      expedienteId: expIds[1],
      fecha: "2026-06-15",
      hora: "10:30",
      tipo: "audiencia" as const,
      titulo: "Audiencia de cierre T-089-2025 - Programada",
      descripcion: "Audiencia de cierre y alegatos finales programada. Partes deben presentar sus conclusiones sobre la prueba rendida.",
      actor: "Sistema Judicial",
      fuente: "pjud",
    },
    {
      causaId: causaIds[3],
      expedienteId: expIds[3],
      fecha: "2024-09-05",
      hora: "08:45",
      tipo: "ingreso" as const,
      titulo: "Ingreso demanda accidente del trabajo O-178-2024",
      descripcion: "Demanda de indemnización de perjuicios por accidente del trabajo. Caída desde altura de 4 metros sin arnés de seguridad.",
      actor: "Valentina Herrera Soto",
      fuente: "pjud",
    },
    {
      causaId: causaIds[3],
      expedienteId: expIds[3],
      fecha: "2026-05-15",
      hora: "15:00",
      tipo: "cambio_estado" as const,
      titulo: "Causa O-178-2024 entra en estado de acuerdo",
      descripcion: "Luego de 3 audiencias de prueba, el tribunal declaró la causa en estado de acuerdo para dictar sentencia definitiva.",
      actor: "Juez Héctor Espinoza Carrasco",
      fuente: "pjud",
    },
    {
      causaId: causaIds[4],
      expedienteId: expIds[4],
      fecha: "2025-02-28",
      hora: "16:30",
      tipo: "sentencia" as const,
      titulo: "Sentencia definitiva T-512-2024",
      descripcion: "Sentencia definitiva acogió demanda. Condena a Retail Patagonia Ltda. a pagar nulidad de despido más remuneraciones caídas por $4.200.000.",
      actor: "Jueza Rosa Morales Iturrieta",
      fuente: "pjud",
    },
    {
      causaId: causaIds[6],
      expedienteId: null,
      fecha: "2026-04-20",
      hora: "11:00",
      tipo: "resolucion" as const,
      titulo: "Resolución de embargo - T-321-2025",
      descripcion: "Juez decretó embargo sobre bienes inmuebles de Guardex Ltda. Se oficia al Conservador de Bienes Raíces de Antofagasta.",
      actor: "Juez Roberto Pizarro Vargas",
      fuente: "pjud",
    },
  ] as any);

  // ─── 6. NOTAS ────────────────────────────────────────────────────
  console.log("  [6/10] Notas...");
  await db.insert(notas).values([
    {
      contenido: "ESTRATEGIA: En caso Martínez Rojas, fortalecer argumento sobre falta de carta de aviso. El despido fue verbal según cliente. Buscar testigos que puedan corroborar. Solicitar correos electrónicos vía art. 453 CT.",
      causaId: causaIds[0],
      expedienteId: expIds[0],
      autor: "Valentina Herrera Soto",
      tipo: "estrategia" as const,
    },
    {
      contenido: "CLIENTE: Roberto Martínez Rojas llamó el 22/05/2026. Muy angustiado por situación económica. Tiene 2 hijos menores. Necesita resolución rápida o acuerdo. Disponible para reunión cualquier día de semana a partir de las 18:00 hrs. Tel: +56 9 8765 4321.",
      causaId: causaIds[0],
      expedienteId: expIds[0],
      autor: "Diego Castillo Muñoz",
      tipo: "cliente" as const,
    },
    {
      contenido: "PROCESAL: Verificar si Servicios Industriales del Sur Ltda. fue notificada correctamente. El receptor judicial indicó que hubo dificultades para encontrar a representante legal. Revisar si se realizó notificación por aviso según art. 443 CT.",
      causaId: causaIds[0],
      expedienteId: expIds[0],
      autor: "Valentina Herrera Soto",
      tipo: "procesal" as const,
    },
    {
      contenido: "ESTRATEGIA TUTELA: En caso Vargas Flores, la clave es demostrar el nexo causal entre el inicio del embarazo y el deterioro de las condiciones laborales. Compilar: (1) correos con hostigamiento, (2) evaluaciones de desempeño antes y después del embarazo, (3) testimonios de compañeras. La jurisprudencia CS es clara en que la carga de la prueba se invierte al empleador.",
      causaId: causaIds[1],
      expedienteId: expIds[1],
      autor: "Valentina Herrera Soto",
      tipo: "estrategia" as const,
    },
    {
      contenido: "CLIENTE: Claudia Vargas Flores informó que hay una segunda trabajadora (Marcela Opazo) que también fue despedida estando embarazada en la misma empresa. Podría ser relevante como prueba de conducta discriminatoria sistemática. Contactar para posible declaración de testigo.",
      causaId: causaIds[1],
      expedienteId: expIds[1],
      autor: "Diego Castillo Muñoz",
      tipo: "cliente" as const,
    },
    {
      contenido: "PROCESAL: En causa Fernández Contreras, el informe pericial del Dr. Alejandro Soto (médico laboral) determinó 40% de incapacidad permanente parcial. Esto equivale aproximadamente a 140 días de tratamiento. El monto indemnizatorio estimado supera los $45.000.000 según baremo actualizado.",
      causaId: causaIds[3],
      expedienteId: expIds[3],
      autor: "Valentina Herrera Soto",
      tipo: "procesal" as const,
    },
    {
      contenido: "EVIDENCIA: En causa Pérez Nahuelqui, AFP Provida emitió certificado de deuda que acredita $8.200.000 en cotizaciones no enteradas para el período enero 2022 - diciembre 2024. Este certificado es prueba directa e irrefutable de la deuda previsional.",
      causaId: causaIds[2],
      expedienteId: expIds[2],
      autor: "Sebastián Moya Lagos",
      tipo: "evidencia" as const,
    },
    {
      contenido: "ESTRATEGIA: Para el recurso de nulidad en causa Torres Iturra, la causal más sólida es la infracción de ley en la valoración de la prueba. El tribunal no ponderó adecuadamente el correo del gerente que admitía el no pago de cotizaciones. Citar SCS Rol 45.678-2025 como precedente.",
      causaId: causaIds[4],
      expedienteId: expIds[4],
      autor: "Sebastián Moya Lagos",
      tipo: "estrategia" as const,
    },
  ] as any);

  // ─── 7. HONORARIOS ───────────────────────────────────────────────
  console.log("  [7/10] Honorarios...");
  await db.insert(honorarios).values([
    {
      causaId: causaIds[0],
      expedienteId: expIds[0],
      cliente: "Roberto Martínez Rojas",
      concepto: "Honorarios causa T-234-2025 - Despido injustificado (primera instancia)",
      tipo: "honorario" as const,
      monto: 2500000,
      montoPagado: 1250000,
      moneda: "CLP",
      estado: "pagado_parcial" as const,
      formaPago: "transferencia" as const,
      numCuotas: 2,
      cuotaActual: 1,
      fechaVencimiento: "2026-06-30",
      facturado: true,
      numeroFactura: "FAC-2025-0234",
      observaciones: "Primera cuota pagada al inicio. Segunda cuota vence 30 de junio.",
    },
    {
      causaId: causaIds[1],
      expedienteId: expIds[1],
      cliente: "Claudia Vargas Flores",
      concepto: "Honorarios tutela derechos fundamentales T-089-2025",
      tipo: "honorario" as const,
      monto: 4500000,
      montoPagado: 4500000,
      moneda: "CLP",
      estado: "pagado" as const,
      formaPago: "transferencia" as const,
      numCuotas: 3,
      cuotaActual: 3,
      fechaVencimiento: "2026-04-30",
      fechaPago: "2026-04-28",
      facturado: true,
      numeroFactura: "FAC-2025-0312",
      observaciones: "Honorarios pagados en 3 cuotas. Caso concluirá en junio.",
    },
    {
      causaId: causaIds[2],
      expedienteId: expIds[2],
      cliente: "Luis Pérez Nahuelqui",
      concepto: "Honorarios cobro cotizaciones previsionales C-456-2025",
      tipo: "honorario" as const,
      monto: 1800000,
      montoPagado: 0,
      moneda: "CLP",
      estado: "pendiente" as const,
      formaPago: "transferencia" as const,
      numCuotas: 1,
      cuotaActual: 0,
      fechaVencimiento: "2026-05-31",
      facturado: false,
      observaciones: "Cliente acordó pagar al recibir sentencia favorable.",
    },
    {
      causaId: causaIds[3],
      expedienteId: expIds[3],
      cliente: "Manuel Fernández Contreras",
      concepto: "Honorarios accidente del trabajo O-178-2024 - Primera instancia",
      tipo: "honorario" as const,
      monto: 5000000,
      montoPagado: 2000000,
      moneda: "CLP",
      estado: "pagado_parcial" as const,
      formaPago: "cuota" as const,
      numCuotas: 5,
      cuotaActual: 2,
      fechaVencimiento: "2026-08-31",
      facturado: true,
      numeroFactura: "FAC-2024-0178",
      observaciones: "Caso de alto riesgo y complejidad. Honorarios acordados en 5 cuotas mensuales.",
    },
    {
      causaId: causaIds[4],
      expedienteId: expIds[4],
      cliente: "Ana Torres Iturra",
      concepto: "Consulta y análisis recurso de nulidad T-512-2024",
      tipo: "consulta" as const,
      monto: 350000,
      montoPagado: 0,
      moneda: "CLP",
      estado: "vencido" as const,
      formaPago: "efectivo" as const,
      numCuotas: 1,
      cuotaActual: 0,
      fechaVencimiento: "2026-04-30",
      facturado: false,
      observaciones: "Honorario por preparación recurso de nulidad. Vencido sin pago. Contactar cliente.",
    },
    {
      causaId: causaIds[6],
      expedienteId: null,
      cliente: "Carlos Jara Sepúlveda",
      concepto: "Honorarios ejecución de sentencia T-321-2025",
      tipo: "honorario" as const,
      monto: 800000,
      montoPagado: 0,
      moneda: "CLP",
      estado: "moroso" as const,
      formaPago: "transferencia" as const,
      numCuotas: 1,
      cuotaActual: 0,
      fechaVencimiento: "2026-03-31",
      facturado: true,
      numeroFactura: "FAC-2025-0567",
      observaciones: "Dos meses de mora. Enviar carta de cobro formal.",
    },
    {
      causaId: causaIds[5],
      expedienteId: null,
      cliente: "Patricia Sanhueza Bravo",
      concepto: "Consulta inicial y evaluación caso despido injustificado",
      tipo: "consulta" as const,
      monto: 120000,
      montoPagado: 120000,
      moneda: "CLP",
      estado: "pagado" as const,
      formaPago: "efectivo" as const,
      numCuotas: 1,
      cuotaActual: 1,
      fechaVencimiento: "2026-04-08",
      fechaPago: "2026-04-08",
      facturado: false,
      observaciones: "Consulta inicial. Se formalizó contrato de servicios para causa M-045-2026.",
    },
    {
      causaId: null,
      expedienteId: expIds[0],
      cliente: "Roberto Martínez Rojas",
      concepto: "Gastos de receptor judicial - Notificaciones y diligencias T-234-2025",
      tipo: "gasto" as const,
      monto: 185000,
      montoPagado: 185000,
      moneda: "CLP",
      estado: "pagado" as const,
      formaPago: "transferencia" as const,
      numCuotas: 1,
      cuotaActual: 1,
      fechaVencimiento: "2025-03-10",
      fechaPago: "2025-03-08",
      facturado: false,
      observaciones: "Gastos de receptor judicial para notificaciones procesales. Reembolsado por cliente.",
    },
    {
      causaId: causaIds[2],
      expedienteId: expIds[2],
      cliente: "Luis Pérez Nahuelqui",
      concepto: "Tasas judiciales y gastos procesales C-456-2025",
      tipo: "tasa" as const,
      monto: 95000,
      montoPagado: 0,
      moneda: "CLP",
      estado: "pendiente" as const,
      formaPago: "transferencia" as const,
      numCuotas: 1,
      cuotaActual: 0,
      fechaVencimiento: "2026-06-15",
      facturado: false,
      observaciones: "Tasas de tramitación. Cliente con beneficio de pobreza - verificar exención.",
    },
    {
      causaId: causaIds[3],
      expedienteId: expIds[3],
      cliente: "Manuel Fernández Contreras",
      concepto: "Honorarios perito médico laboral - Informe Dr. Soto",
      tipo: "gasto" as const,
      monto: 950000,
      montoPagado: 950000,
      moneda: "CLP",
      estado: "pagado" as const,
      formaPago: "transferencia" as const,
      numCuotas: 1,
      cuotaActual: 1,
      fechaVencimiento: "2026-04-01",
      fechaPago: "2026-03-28",
      facturado: true,
      numeroFactura: "FAC-2026-0089",
      observaciones: "Pago a perito médico por informe de incapacidad. A recuperar al ganar el juicio.",
    },
  ] as any);

  // ─── 8. LEY KARIN - DENUNCIAS ────────────────────────────────────
  console.log("  [8/10] Ley Karin - Denuncias...");
  const denunciasData = await db.insert(leykarinDenuncias).values([
    {
      codigo: "LK-2026-001",
      fechaRecepcion: "2026-04-10",
      fechaHechos: "2026-03-15",
      tipo: "acoso_laboral" as const,
      modo: "escrito" as const,
      denunciante: "María González Reyes",
      denunciado: "Pedro Castillo Vega",
      rutDenunciante: "16.789.012-4",
      rutDenunciado: "10.234.567-8",
      area: "Departamento de Operaciones",
      cargoDenunciante: "Analista de Procesos",
      cargoDenunciado: "Jefe de Operaciones",
      descripcionHechos: "La trabajadora denuncia hostigamiento reiterado por parte de su jefe directo desde enero de 2026. Conductas incluyen: exclusión sistemática de reuniones de equipo, asignación de tareas degradantes, gritos delante de compañeros y amenazas veladas de despido condicionadas a no denunciar. Hay registro en correos electrónicos.",
      testigos: "Carmen Pérez (analista), Roberto Sánchez (supervisor área bodega)",
      evidencia: "Correos electrónicos 15/01, 22/02 y 10/03/2026. Registro de asignación de tareas irregular.",
      estado: "investigacion" as const,
      prioridad: "alta" as const,
      investigador: "Valentina Herrera Soto",
      fechaInicioInvestigacion: "2026-04-17",
      fechaPlazo: "2026-05-17",
      diasPlazo: 30,
      medidasCautelares: "Separación física de trabajadora del área del denunciado. Cambio temporal de piso. Aprobado por RRHH el 12/04/2026.",
      anonimizada: false,
    },
    {
      codigo: "LK-2025-018",
      fechaRecepcion: "2025-11-05",
      fechaHechos: "2025-10-20",
      tipo: "acoso_sexual" as const,
      modo: "presencial" as const,
      denunciante: "Francisca Morales Díaz",
      denunciado: "Antonio Rivas Herrera",
      rutDenunciante: "19.345.678-1",
      rutDenunciado: "7.654.321-0",
      area: "Gerencia Comercial",
      cargoDenunciante: "Ejecutiva de Ventas",
      cargoDenunciado: "Gerente Comercial",
      descripcionHechos: "Insinuaciones sexuales repetidas durante reuniones, tocaciones no consentidas en hombros y cabello, y envío de mensajes de WhatsApp con contenido inapropiado. La trabajadora tiene capturas de pantalla de los mensajes.",
      testigos: "Ninguno directo. Una colega escuchó comentarios inapropiados del gerente.",
      evidencia: "Capturas de pantalla WhatsApp. Correo de RRHH reconociendo anterior queja informal.",
      estado: "concluida" as const,
      prioridad: "critica" as const,
      investigador: "Valentina Herrera Soto",
      fechaInicioInvestigacion: "2025-11-12",
      fechaPlazo: "2025-12-12",
      fechaResolucion: "2025-12-10",
      diasPlazo: 30,
      medidasCautelares: "Suspensión temporal del denunciado con goce de remuneraciones.",
      medidasDefinitivas: "Despido del denunciado por falta grave a la probidad (Art. 160 N°1 b) CT).",
      resolucion: "Investigación concluyó con comprobación de los hechos denunciados. Se aplicó medida disciplinaria máxima: despido por falta grave.",
      accionesTomadas: "Despido del Sr. Rivas ejecutado el 12/12/2025. Se informó a la Dirección del Trabajo. Se implementó protocolo de prevención Ley Karin en la empresa.",
      anonimizada: false,
    },
    {
      codigo: "LK-2026-005",
      fechaRecepcion: "2026-05-02",
      fechaHechos: "2026-04-28",
      tipo: "violencia_laboral" as const,
      modo: "presencial" as const,
      denunciante: null,
      denunciado: "Jorge Fernández Ortiz",
      rutDenunciante: null,
      rutDenunciado: "12.876.543-2",
      area: "Planta de Producción",
      cargoDenunciante: "Operario (anónimo)",
      cargoDenunciado: "Supervisor de Producción",
      descripcionHechos: "Denuncia anónima reporta que el supervisor agredió verbalmente de manera violenta a tres operarios frente a toda la línea de producción, usando insultos y amenazas. Habría arrojado un objeto sobre una mesa. Ambiente de trabajo degradante y temeroso reportado por múltiples trabajadores.",
      testigos: "Al menos 5 operarios presentes (se deben identificar en investigación).",
      evidencia: "Denuncia anónima. Cámaras de seguridad en planta pueden registrar el episodio.",
      estado: "recepcionada" as const,
      prioridad: "alta" as const,
      investigador: null,
      fechaInicioInvestigacion: null,
      fechaPlazo: "2026-06-02",
      diasPlazo: 30,
      medidasCautelares: null,
      anonimizada: true,
    },
  ] as any).$returningId();

  const denunciaIds = denunciasData.map((d: { id: number }) => d.id);

  // ─── 9. LEY KARIN - ACTUACIONES ──────────────────────────────────
  console.log("  [9/10] Ley Karin - Actuaciones...");
  await db.insert(leykarinActuaciones).values([
    {
      denunciaId: denunciaIds[0],
      fecha: "2026-04-10",
      tipo: "recepcion" as const,
      descripcion: "Recepción formal de denuncia por escrito. Revisión de admisibilidad: la denuncia cumple con los requisitos del Art. 211-A CT y Ley 21.643. Se notifica al trabajador denunciante sobre los plazos del proceso.",
      actor: "Diego Castillo Muñoz",
      horaInicio: "10:00",
      horaFin: "11:30",
    },
    {
      denunciaId: denunciaIds[0],
      fecha: "2026-04-17",
      tipo: "evaluacion" as const,
      descripcion: "Evaluación inicial de la denuncia. Se verifican los hechos preliminares y se determina que existen antecedentes suficientes para iniciar investigación formal. Se adoptan medidas cautelares: separación física de las partes.",
      actor: "Valentina Herrera Soto",
      horaInicio: "09:00",
      horaFin: "10:30",
    },
    {
      denunciaId: denunciaIds[0],
      fecha: "2026-04-25",
      tipo: "entrevista" as const,
      descripcion: "Entrevista a la trabajadora denunciante María González. Declaración detallada de los hechos. Se reciben correos electrónicos como evidencia. Declaración grabada con consentimiento.",
      actor: "Valentina Herrera Soto",
      horaInicio: "14:00",
      horaFin: "16:00",
    },
    {
      denunciaId: denunciaIds[1],
      fecha: "2025-11-12",
      tipo: "investigacion" as const,
      descripcion: "Inicio formal de investigación caso LK-2025-018. Se adopta medida cautelar de suspensión del denunciado con goce de remuneraciones. Se notifica a ambas partes por escrito del inicio del proceso.",
      actor: "Valentina Herrera Soto",
      horaInicio: "09:00",
      horaFin: "10:00",
    },
    {
      denunciaId: denunciaIds[1],
      fecha: "2025-12-10",
      tipo: "resolucion" as const,
      descripcion: "Resolución final caso LK-2025-018. La investigación comprobó los hechos denunciados. Se recomienda despido por falta grave (Art. 160 N°1 b) CT). La empresa acepta la recomendación y ejecuta el despido el 12/12/2025. Se informa a Dirección del Trabajo.",
      actor: "Valentina Herrera Soto",
      horaInicio: "11:00",
      horaFin: "12:30",
      documento: "Informe Final Investigación LK-2025-018 - 35 páginas. Conclusiones: hechos acreditados. Medida: Despido Art. 160 N°1 b CT.",
    },
  ] as any);

  // ─── 10. DIARIO OFICIAL NORMAS ───────────────────────────────────
  console.log("  [10/10] Diario Oficial - Normas...");
  await db.insert(diarioOficialNormas).values([
    {
      numeroDO: "43.521",
      fechaPublicacion: "2026-05-20",
      tipo: "decreto" as const,
      organismo: "Ministerio del Trabajo y Previsión Social",
      titulo: "Decreto N°156 que establece reglamento sobre jornada laboral adaptable para empresas de hasta 50 trabajadores",
      extracto: "El presente decreto reglamenta la aplicación de la jornada laboral adaptable conforme a la Ley 21.561 (40 horas). Establece procedimientos de implementación, requisitos de acuerdo colectivo o individual, y mecanismos de supervisión de la Dirección del Trabajo. Aplica a empresas con dotación de hasta 50 trabajadores.",
      materia: "laboral" as const,
      urlOriginal: "https://www.diariooficial.interior.gob.cl/publicaciones/2026/05/20/43521/01/2689234.pdf",
      numeroNorma: "156",
      anoNorma: 2026,
      vigente: true,
      articulosRelevantes: "Art. 1-8: Ámbito de aplicación. Art. 9-15: Procedimiento de implementación. Art. 16-20: Supervisión DT.",
      alertaGenerada: true,
      procesadoRag: false,
    },
    {
      numeroDO: "43.498",
      fechaPublicacion: "2026-05-01",
      tipo: "decreto" as const,
      organismo: "Ministerio del Trabajo y Previsión Social",
      titulo: "Decreto Supremo N°48 que fija el Ingreso Mínimo Mensual para el período mayo 2026 - abril 2027",
      extracto: "Se fija el Ingreso Mínimo Mensual (IMM) en $550.000 para trabajadores mayores de 18 años y menores de 65 años. El IMM para mayores de 65 y menores de 18 años queda fijado en $410.000. Vigencia desde el 1 de mayo de 2026.",
      materia: "laboral" as const,
      urlOriginal: "https://www.diariooficial.interior.gob.cl/publicaciones/2026/05/01/43498/01/2687890.pdf",
      numeroNorma: "48",
      anoNorma: 2026,
      vigente: true,
      articulosRelevantes: "Art. 1: IMM $550.000 para trabajadores 18-65 años. Art. 2: IMM $410.000 para otros tramos etarios. Art. 3: Vigencia.",
      alertaGenerada: true,
      procesadoRag: true,
    },
    {
      numeroDO: "43.467",
      fechaPublicacion: "2026-04-10",
      tipo: "resolucion" as const,
      organismo: "Dirección del Trabajo",
      titulo: "Resolución Exenta N°234 que aprueba protocolo de actuación para fiscalización en materia de Ley Karin (Ley 21.643)",
      extracto: "La Dirección del Trabajo aprueba el protocolo interno de actuación para fiscalización del cumplimiento de la Ley 21.643 sobre prevención y sanción del acoso laboral, sexual y violencia en el trabajo. Establece procedimientos de denuncia, investigación y seguimiento para empleadores con 10 o más trabajadores.",
      materia: "laboral" as const,
      urlOriginal: "https://www.dt.gob.cl/portal/1628/articles-167890_recurso_1.pdf",
      numeroNorma: "234",
      anoNorma: 2026,
      vigente: true,
      articulosRelevantes: "Título I: Ámbito aplicación. Título II: Proceso denuncia. Título III: Investigación. Título IV: Medidas. Título V: Sanciones.",
      alertaGenerada: false,
      procesadoRag: false,
    },
    {
      numeroDO: "43.389",
      fechaPublicacion: "2026-02-15",
      tipo: "ley" as const,
      organismo: "Congreso Nacional / Ministerio del Trabajo",
      titulo: "Ley N°21.789 que modifica el Código del Trabajo en materia de licencias médicas preventivas para trabajadores con enfermedades crónicas",
      extracto: "Modifica el Código del Trabajo incorporando el derecho de los trabajadores con enfermedades crónicas certificadas (diabetes, hipertensión, enfermedades autoinmunes) a solicitar licencias médicas preventivas anuales de hasta 5 días hábiles, sin descuento en remuneración. Regula el procedimiento ante COMPIN.",
      materia: "laboral" as const,
      urlOriginal: "https://www.bcn.cl/leychile/navegar?idNorma=1234567",
      numeroNorma: "21789",
      anoNorma: 2026,
      vigente: true,
      articulosRelevantes: "Art. 1: Incorpora Art. 198 quinquies CT. Art. 2: Modifica Art. 199 CT. Art. 3: Reglamento. Art. 4: Vigencia 90 días publicación.",
      alertaGenerada: true,
      procesadoRag: false,
    },
    {
      numeroDO: "43.312",
      fechaPublicacion: "2025-12-01",
      tipo: "circular" as const,
      organismo: "Superintendencia de Pensiones",
      titulo: "Circular N°2345 sobre criterios de fiscalización del pago oportuno de cotizaciones previsionales por empleadores",
      extracto: "Establece los criterios y procedimientos que aplicará la Superintendencia de Pensiones para la fiscalización del cumplimiento oportuno del pago de cotizaciones previsionales. Define los umbrales de deuda que activarán procedimientos de cobranza ejecutiva y las sanciones aplicables a empleadores morosos reincidentes.",
      materia: "laboral" as const,
      urlOriginal: "https://www.spensiones.cl/portal/institucional/594/articles-14789_recurso_1.pdf",
      numeroNorma: "2345",
      anoNorma: 2025,
      vigente: true,
      articulosRelevantes: "Sección I: Umbrales de fiscalización. Sección II: Procedimiento cobranza. Sección III: Sanciones empleadores morosos.",
      alertaGenerada: false,
      procesadoRag: true,
    },
  ] as any);

  console.log("  [SC] Datos de servicios completos insertados correctamente.\n");
}
